# Makefile for the focaltech touchscreen drivers.

#focaltech_ts-y += focaltech_core.o focaltech_flash.o

#obj-$(CONFIG_TOUCHSCREEN_FTS_CORE)	+= focaltech_ts.o
#obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)	+= focaltech_spi.o

focaltech_ts-y += focaltech_spi.o focaltech_core.o focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)	+= focaltech_ts.o
